name: update translations

on:
  schedule:
    - cron: 42 7 * * *
permissions:
  contents: write
jobs:
  update_translations:
    name: update translations
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build translation
      run: |
        python main.py
    - name: Upload translation
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        if git commit -am "Update translation at $(date)"; then
          git push
        fi    
